---
# Ansible playbook
#
# @author Roy Rim

- hosts: all
  gather_facts: yes

  tasks:
    - name: yum install epel-release
      become: yes
      yum:
        name: epel-release
        state: latest

    - name: yum upgrade python-setuptools
      become: yes
      yum:
        name: python-setuptools
        state: latest

    - name: yum installs
      become: yes
      yum:
        name: git, gcc, automake, autoconf, libtool, cmake3, java-1.7.0, java-1.8.0, maven, python-virtualenv.noarch, scons.noarch
        state: latest

    - name: git mongodb c driver
      git:
        repo: https://github.com/mongodb/mongo-c-driver.git
        dest: /home/vagrant/mongo-c-driver
        clone: yes

    - name: git mongodb cxx driver
      git:
        repo: https://github.com/mongodb/mongo-cxx-driver.git
        dest: /home/vagrant/mongo-cxx-driver
        clone: yes

    - name: git mongo
      git:
        repo: https://github.com/mongodb/mongo.git
        dest: /home/vagrant/mongo
        clone: yes
    
    - name: git mongodb java driver
      git:
        repo: https://github.com/mongodb/mongo-java-driver.git
        dest: /home/vagrant/mongo-java-driver
        clone: yes
    
    - name: git simple mongodb java maven starter project
      git:
        repo: https://github.com/mongoroy/mongodb-maven-starter.git
        dest: /home/vagrant/mongodb-maven-starter
        clone: yes
    
    - name: install nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
        creates=/home/vagrant/.nvm/nvm.sh

    - name: install nodejs using nvm
      shell: >
        /bin/bash -c "source ~/.nvm/nvm.sh && nvm install node"

    - name: install mongodb m via npm
      shell: >
        npm install -g m

    - name: create mongodb directory
      file:
        path: /home/vagrant/mongodb/bin
        state: directory

    - name: Adding M_PREFIX for mongodb m
      lineinfile: 
        dest: /home/vagrant/.bashrc 
        line: 'export M_PREFIX=~/mongodb'
        insertafter: 'EOF' 
        state: present

    - name: Adding M_PREFIX/bin to PATH
      lineinfile: 
        dest: /home/vagrant/.bashrc 
        line: 'export PATH=$PATH:~/mongodb/bin'
        insertafter: 'EOF' 
        state: present

    - name: Download pip
      shell: >
        wget https://bootstrap.pypa.io/get-pip.py
        creates=/home/vagrant/get-pip.py

    - name: Install pip
      shell: >
        sudo python get-pip.py
        creates=/usr/bin/pip

    - name: Install mtools
      become: yes
      pip:
        name: pymongo, numpy, matplotlib, mtools

